"""Add followers table

Revision ID: 927738faf5ae
Revises: b7c5fd93ef9b
Create Date: 2022-07-23 17:11:31.216768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927738faf5ae'
down_revision = 'b7c5fd93ef9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
